name: Public distributia pe PyPI si TestPyPI

on:
  push:
  pull_request:

jobs:
  build-n-publish:
    name: Creez si public distributia python
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Initializez Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Instalez dependintele
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Testez cu flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build binary wheel and a source tarball
      run: python TipyVoda_timechecker sdist
    - name: Public distributia pe Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
